version: '3.8'

services:
  php:
    build: ./docker/php
    env_file: phpfile.env
    ports:
      - 80:80
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/html:/var/www/html
      - ./docker/log/apache2:/var/log/apache2
      - ./docker/log/xdebug:/var/log/xdebug
  service_postgres:
    image: postgres:15
    container_name: container_postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb01
    ports: 
      - "5433:5432"
    volumes:
      - volume_postgres:/var/lib/postgresql/data
      - ./postgres_service/initdb.d:/docker-entrypoint-initdb.d

  service_pgadmin:
    image: dpage/pgadmin4:7
    container_name: container_pgadmin
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - service_postgres

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga


